package GUI;

import Accounts.EndUser;
import Accounts.EndUserProxy;
import Products.Drinks.DrinksCategory;
import Products.ProductCategory;
import Products.Size;
import Products.Snacks.SnackCategory;
import java.util.ArrayList;
import javax.swing.JOptionPane;

public class Ordering extends javax.swing.JFrame {

    private static final String NONE_SELECTED = "---";
    
    public Ordering() {
        initComponents();
        
        EndUser endUser = new EndUserProxy();
        ArrayList availableProducts =  endUser.getAvailableProducts();    
        
        for (Object obj : availableProducts)
        {
            String itemName = (String) obj;
            
            if (itemName.equals(DrinksCategory.Coffee.toString()))
            {
                cmbSize.addItem(Size.Regular.toString());
                cmbSize.addItem(Size.Medium.toString());
                cmbSize.addItem(Size.Large.toString());
            }
            else if ((itemName.equals(SnackCategory.CurryPuff.toString()))
                    || (itemName.equals(SnackCategory.Kuih.toString()))
                    || (itemName.equals(SnackCategory.Pau.toString()))
                    || (itemName.equals(SnackCategory.Sandwich.toString())))
            {
                cmbSnack.addItem(itemName);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmbSize = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        cmbTopping = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cmbIce = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        cmbMilk = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        cmbSugar = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        cmbSnack = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        cmbCheese = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        cmbLettuce = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        cmbOnion = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        cmbTuna = new javax.swing.JComboBox<>();
        btnOrder = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Coffee Size:");

        cmbSize.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---" }));

        jLabel2.setText("Topping:");

        cmbTopping.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No Topping", "Sprinkle", "Cream" }));

        jLabel3.setText("Ice:");

        cmbIce.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No Ice", "Less Ice", "Regular Ice", "More Ice" }));

        jLabel4.setText("Milk:");

        cmbMilk.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No Milk", "Less Milk", "Regular Milk", "More Milk" }));
        cmbMilk.setToolTipText("");

        jLabel5.setText("Sugar:");

        cmbSugar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No Sugar", "Less Sugar", "Regular Sugar", "More Sugar" }));

        jLabel9.setText("Snack:");

        cmbSnack.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---" }));

        jLabel12.setText("Cheese:");

        cmbCheese.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No Cheese", "Cheese" }));

        jLabel8.setText("Lettuce:");

        cmbLettuce.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No Lettuce", "Lettuce" }));

        jLabel10.setText("Onion:");

        cmbOnion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No Onion", "Onion" }));

        jLabel11.setText("Tuna:");

        cmbTuna.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No Tuna", "Tuna" }));

        btnOrder.setText("Order");
        btnOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderActionPerformed(evt);
            }
        });

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        jLabel6.setText("Ordering");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cmbTopping, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(cmbIce, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel11))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(cmbSugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel10))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(cmbMilk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel12))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(cmbSize, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(94, 94, 94)
                                .addComponent(jLabel9)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbSnack, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbCheese, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbOnion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbTuna, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbLettuce, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(btnOrder)
                        .addGap(18, 18, 18)
                        .addComponent(btnExit)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel9)
                    .addComponent(cmbSnack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbMilk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(cmbCheese, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmbSugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(cmbOnion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbIce, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(cmbTuna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbTopping, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(cmbLettuce, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOrder)
                    .addComponent(btnExit))
                .addGap(28, 28, 28))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderActionPerformed
        EndUser student = new EndUserProxy();

        if (!(cmbSnack.getSelectedItem().toString().equals(NONE_SELECTED)) || !(cmbSize.getSelectedItem().toString().equals(NONE_SELECTED)))
        {
            if (!cmbSnack.getSelectedItem().toString().equals(NONE_SELECTED))
            {
                ArrayList<String> addon = new ArrayList<String>();
                String product = cmbSnack.getSelectedItem().toString().replaceAll("\\s+","");
                addon.add(cmbLettuce.getSelectedItem().toString().replaceAll("\\s+",""));
                addon.add(cmbOnion.getSelectedItem().toString().replaceAll("\\s+",""));
                addon.add(cmbTuna.getSelectedItem().toString().replaceAll("\\s+",""));
                addon.add(cmbCheese.getSelectedItem().toString().replaceAll("\\s+",""));
                student.order(ProductCategory.Snack.toString(), product, addon);
            }
            
            if (!cmbSize.getSelectedItem().toString().equals(NONE_SELECTED))
            {
                ArrayList<String> addon = new ArrayList<String>();
                String product = DrinksCategory.Coffee.toString().replaceAll("\\s+","");
                addon.add(cmbTopping.getSelectedItem().toString().replaceAll("\\s+",""));
                addon.add(cmbIce.getSelectedItem().toString().replaceAll("\\s+",""));
                addon.add(cmbMilk.getSelectedItem().toString().replaceAll("\\s+",""));
                addon.add(cmbSugar.getSelectedItem().toString().replaceAll("\\s+",""));
                addon.add(cmbSize.getSelectedItem().toString().replaceAll("\\s+",""));
                student.order(ProductCategory.Drinks.toString(), product, addon);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Invalid order! Please select a drink or a snack!");
        }
    }//GEN-LAST:event_btnOrderActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        new UserLogin().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ordering.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ordering.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ordering.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ordering.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Ordering().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnOrder;
    private javax.swing.JComboBox<String> cmbCheese;
    private javax.swing.JComboBox<String> cmbIce;
    private javax.swing.JComboBox<String> cmbLettuce;
    private javax.swing.JComboBox<String> cmbMilk;
    private javax.swing.JComboBox<String> cmbOnion;
    private javax.swing.JComboBox<String> cmbSize;
    private javax.swing.JComboBox<String> cmbSnack;
    private javax.swing.JComboBox<String> cmbSugar;
    private javax.swing.JComboBox<String> cmbTopping;
    private javax.swing.JComboBox<String> cmbTuna;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
